### ISSUE TITLE
Biomarker Ontology on Biomarker webpage

### ISSUE THREAD

**Issue by DaniallMasood** [clinical-biomarkers/biomarker-partnership#118]
Implement ontology on the biomarker webpage

**Comment by seankim658** [comment]
Looking into this.

**Comment by DaniallMasood** [comment]
https://disease-ontology.org/do

something like this. Can reach out to Allen Baron to talk to his team and get the code behind this if needed

**Comment by seankim658** [comment]
Closing as ticket has moved [here](https://github.com/clinical-biomarkers/biomarker-issue-repo/issues/3).
