### ISSUE TITLE
Biomarker Scoring

### ISSUE THREAD

**Issue by DaniallMasood** [clinical-biomarkers/biomarker-partnership#131]
How should biomarker scores. Begin to look into algorithm based on publications, FDA approval, EHR, etc

Look at example in IDG. Discuss with Jeremy

**Comment by seankim658** [comment]
Another idea is to add a hard cap to generic cancer biomarkers. For example, generic cancer biomarkers can be capped at a score of 2 (which would require 3 PMIDs to reach since generic cancer biomarkers get a -1 automatically).

**Comment by seankim658** [comment]
The first version of this tool has been built, it's in [this](https://github.com/clinical-biomarkers/biomarker-score-calculator) repo. Right now the tool just takes either user overwritten weights or the default weights and calculates a score for each biomarker in a set of data files. It then outputs to a JSON file with the `biomarker_id` and a `score`. The clinical usage weight is not used right now as we don't have this data yet.
