### ISSUE TITLE
Redirect link to biomarker portal

### ISSUE THREAD

**Issue by DaniallMasood** [clinical-biomarkers/biomarker-partnership#147]
Have a redirect link for https://glygen.ccrc.uga.edu/frontend/home/

Something we can put on a slide 

should be https://hivelab.biochemistry.gwu.edu/biomarker-portal

**Comment by seankim658** [comment]
Redirect works on the tst server. Adding to production now as well.

**Comment by seankim658** [comment]
Redirect is live on prod. Closing this ticket.
